import React from 'react'

const PrivacyPolicy = () => {
    return (
        <div className="h-screen w-screen mt-20">
            <div className="py-6 bg-gray-100 text-gray-800">
                <div className="max-w-4xl mx-auto bg-white shadow-md rounded-lg p-8">
                    <h1 className="text-2xl font-bold mt-4 mb-6 text-blue-600">Privacy Policy</h1>

                    <p className="text-gray-700"><strong>Last updated:</strong> September 17, 2024</p>

                    <p className="mt-4">
                        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure
                        of Your information when You use the Service and tells You about Your privacy rights and how the law
                        protects You.
                    </p>

                    <p className="mt-4">
                        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
                        collection and use of information in accordance with this Privacy Policy.
                    </p>

                    <h2 className="text-xl font-semibold mt-8 text-blue-600">Interpretation and Definitions</h2>

                    <h3 className="text-lg font-medium mt-4">Interpretation</h3>
                    <p className="mt-2">
                        The words of which the initial letter is capitalized have meanings defined under the following
                        conditions. The following definitions shall have the same meaning regardless of whether they appear
                        in singular or in plural.
                    </p>

                    <h3 className="text-lg font-medium mt-4">Definitions</h3>
                    <ul className="list-disc pl-6 mt-2 space-y-2">
                        <li><strong>Account:</strong> A unique account created for You to access our Service or parts of our Service.</li>
                        <li><strong>Affiliate:</strong> An entity that controls, is controlled by or is under common control with a party.</li>
                        <li><strong>Application:</strong> Refers to Sky Global Multi Service, the software program provided by the Company.</li>
                        <li><strong>Company:</strong> Refers to Sky Global Multi Service, also referred to as "We", "Us", or "Our".</li>
                        <li><strong>Country:</strong> Myanmar (Burma)</li>
                        <li><strong>Device:</strong> Any device that can access the Service such as a computer, a cellphone, or a digital tablet.</li>
                    </ul>

                    <h2 className="text-xl font-semibold mt-8 text-blue-600">Service</h2>
                    <p className="mt-2">Service refers to the Application.</p>

                    <h3 className="text-lg font-medium mt-4">Service Provider</h3>
                    <p className="mt-2">
                        Service Provider means any natural or legal person who processes the data on behalf of the Company.
                        It refers to third-party companies or individuals employed by the Company to facilitate the Service.
                    </p>

                    <h3 className="text-lg font-medium mt-4">Usage Data</h3>
                    <p className="mt-2">
                        Usage Data refers to data collected automatically, either generated by the use of the Service or from
                        the Service infrastructure itself (for example, the duration of a page visit).
                    </p>

                    <h3 className="text-lg font-medium mt-4">You</h3>
                    <p className="mt-2">
                        You means the individual accessing or using the Service, or the company, or other legal entity on
                        behalf of which such individual is accessing or using the Service, as applicable.
                    </p>

                    <h2 className="text-xl font-semibold mt-8 text-blue-600">Collecting and Using Your Personal Data</h2>

                    <h3 className="text-lg font-medium mt-4">Types of Data Collected</h3>
                    <p className="mt-2">
                        While using Our Service, We may ask You to provide Us with certain personally identifiable information
                        that can be used to contact or identify You. Personally identifiable information may include, but is
                        not limited to Usage Data.
                    </p>

                    <ul className="list-disc pl-6 mt-2 space-y-2">
                        <li>Usage Data</li>
                    </ul>

                    <h3 className="text-lg font-medium mt-4">Usage Data Details</h3>
                    <p className="mt-2">
                        Usage Data is collected automatically when using the Service. It may include information such as Your Device's
                        IP address, browser type, browser version, and pages visited.
                    </p>

                    <p className="mt-2">
                        When You access the Service by or through a mobile device, We may collect certain information automatically,
                        including the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device,
                        Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                    </p>

                    <p className="mt-2">
                        We may also collect information that Your browser sends whenever You visit our Service or when You access the Service
                        by or through a mobile device.
                    </p>

                    <h3 className="text-lg font-medium mt-4">Use of Your Personal Data</h3>
                    <p className="mt-2">
                        The Company may use Personal Data for the following purposes: to provide and maintain our Service, including to monitor the usage of our Service.
                    </p>

                    <h3 className="text-lg font-medium mt-6 text-primary">Information We Collect</h3>

                    <div className="mt-2">
                        <h4 className="font-semibold mt-2">A. Information You Provide Directly</h4>
                        <p className="mt-1">
                            When you use our app to create or generate a CV, you may provide:
                        </p>
                        <ul className="list-disc pl-6 mt-2 space-y-2">
                            <li>Profile photo or image (for inclusion in your CV)</li>
                            <li>Name and contact details</li>
                            <li>Education, experience, and other resume details</li>
                        </ul>
                        <p className="mt-2">
                            This information is used only for generating your CV and is not shared or sold to third parties.
                            If you delete your CV or uninstall the app, we will remove your data from our systems.
                        </p>

                        <h4 className="font-semibold mt-4">B. Information Collected Automatically (AdMob &amp; Analytics)</h4>
                        <p className="mt-1">
                            We use Google AdMob to show ads and improve app performance. AdMob and its partners may automatically collect:
                        </p>
                        <ul className="list-disc pl-6 mt-2 space-y-2">
                            <li>Device identifiers (IDFA / AAID)</li>
                            <li>Approximate location</li>
                            <li>IP address</li>
                            <li>Ad interaction data (views, clicks)</li>
                            <li>App usage statistics</li>
                        </ul>
                        <p className="mt-2">
                            This information may be used for personalized advertising (tracking across apps and websites). Learn more about how Google uses data{" "}
                            <a
                                href="https://policies.google.com/technologies/ads"
                                target="_blank"
                                rel="noopener noreferrer"
                                className="text-blue-500 underline"
                            >
                                here
                            </a>.
                        </p>
                    </div>

                    <h3 className="text-lg font-medium mt-6">How We Use the Information</h3>
                    <p className="mt-2">
                        We use collected data for generating and displaying your CV (user-provided data), improving the quality and relevance
                        of ads (AdMob), and enhancing app performance and user experience. We do not sell your personal data.
                    </p>

                    <h3 className="text-lg font-medium mt-6">Tracking and Advertising</h3>
                    <p className="mt-2">
                        Our app may request permission to track your activity across other companies’ apps and websites for personalized ads.
                        You can manage or disable this at any time:
                    </p>
                    <ul className="list-disc pl-6 mt-2 space-y-2">
                        <li>iOS: Settings → Privacy → Tracking</li>
                        <li>Android: Settings → Google → Ads → Opt out of Ads Personalization</li>
                    </ul>
                    <p className="mt-2">If you deny tracking permission, you’ll still receive ads, but they will be non-personalized.</p>

                    <h3 className="text-lg font-medium mt-6">Data Retention and Deletion</h3>
                    <p className="mt-2">
                        Your photo and CV data are used only for generating the CV. You can request data deletion by contacting us at{" "}
                        <a href="mailto:skyglobalmyanmar@gmail.com" className="text-blue-500 underline">skyglobalmyanmar@gmail.com</a>.
                        AdMob data is managed by Google and subject to their data retention policies.
                    </p>

                    <h2 className="text-xl font-bold mt-14 text-blue-600">Other legal requirements</h2>

                    <h2 className="text-lg font-semibold mt-8 text-blue-600">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</h2>
                    <ul className="list-disc pl-6 mt-2 space-y-2">
                        <li>Comply with a legal obligation</li>
                        <li>Protect and defend the rights or property of the Company</li>
                        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                        <li>Protect the personal safety of Users of the Service or the public</li>
                        <li>Protect against legal liability</li>
                    </ul>

                    <h2 className="text-xl font-semibold mt-8 text-blue-600">Children's Privacy</h2>
                    <p className="mt-4">
                        Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13.
                        If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information.
                    </p>
                    <p className="mt-4">
                        If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent,
                        We may require Your parent's consent before We collect and use that information.
                    </p>

                    <h2 className="text-xl font-semibold mt-8 text-blue-600">Links to Other Websites</h2>
                    <p className="mt-4">
                        Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit.
                    </p>
                    <p className="mt-4">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

                    <h2 className="text-xl font-semibold mt-8 text-blue-600">Changes to this Privacy Policy</h2>
                    <p className="mt-4">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
                    <p className="mt-4">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date.</p>
                    <p className="mt-4">You are advised to review this Privacy Policy periodically for any changes. Changes are effective when posted on this page.</p>

                    <h2 className="text-xl font-semibold mt-8 text-blue-600">Contact Us</h2>
                    <p className="mt-4">If you have any questions about this Privacy Policy, You can contact us:</p>
                    <ul className="list-disc pl-6 mt-2 space-y-2 pb-10">
                        <li>Email: <a href="mailto:skyglobalmyanmar@gmail.com" className="text-blue-500 underline">skyglobalmyanmar@gmail.com</a></li>
                    </ul>
                </div>
            </div>
        </div>
    )
}

export default PrivacyPolicy